---
name: Terraform Live Repo
on:
  push:
    branches:
      - master
    pull_request:
jobs:
  terraform:
    name: Terrafom
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #      - name: Check if commit is tagged
      #        run: git describe --tags --exact-match HEAD

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      #
#      - name: TFLint
#        uses: devops-infra/action-tflint@master

      - name: Run terraform fmt
        id: terraform-fmt
        run: terraform fmt -check -recursive -diff

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true


